apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wazuh/manager
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-indexer-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wazuh/indexer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-dashboard-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wazuh/dashboard
