apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-manager
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
  template:
    metadata:
      labels:
        app: wazuh-manager
    spec:
      containers:
      - name: wazuh-manager
        image: wazuh/wazuh-manager:4.8.2
        ports:
        - containerPort: 1514
        volumeMounts:
        - name: manager-data
          mountPath: /var/ossec
      volumes:
      - name: manager-data
        persistentVolumeClaim:
          claimName: wazuh-manager-pvc
