wazuh:
  manager:
    replicas: 1
    resources:
      limits:
        memory: "1500Mi"
        cpu: "500m"
    persistence:
      enabled: true
      storageClass: wazuh-local-storage
      size: 15Gi

  indexer:
    replicas: 1
    resources:
      limits:
        memory: "2500Mi"
        cpu: "700m"
    persistence:
      enabled: true
      storageClass: wazuh-local-storage
      size: 25Gi

  dashboard:
    replicas: 1
    resources:
      limits:
        memory: "500Mi"
        cpu: "300m"
