apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-indexer-config
  namespace: wazuh
data:
  opensearch.yml: |
    cluster.name: wazuh-cluster
    node.name: wazuh-indexer-0

    network.host: 0.0.0.0
    http.port: 9200

    discovery.type: single-node

    plugins.security.disabled: true
