apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage-class.yaml
  - pvc.yaml
  - indexer-resources.yaml
  - wazuh-resources.yaml
  - dashboard.yaml
  - dashboard-service.yaml
