apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-api
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-api
  template:
    metadata:
      labels:
        app: wazuh-api
    spec:
      volumes:
        - name: wazuh-api-config
          configMap:
            name: wazuh-api-config

      containers:
        - name: wazuh-api
          image: wazuh/wazuh-manager:4.7.3
          ports:
            - containerPort: 55000

          env:
            # Connect API to Manager
            - name: WAZUH_MANAGER
              value: "wazuh-manager-master"

            # API credentials
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password

            # Disable HTTPS for lab
            - name: HTTPS
              value: "false"

          volumeMounts:
            - name: wazuh-api-config
              mountPath: /var/ossec/api/configuration/api.yaml
              subPath: api.yaml
