apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../wazuh
- storage-class.yaml   # ‚Üê ADD as resource

patches:
- path: indexer-resources.yaml
- path: wazuh-resources.yaml
